// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2L8m_IpLDROACmlN00H_Dk3hxaxSaN0Y',
    appId: '1:447473778417:web:88b4cba41ef3106bfa7350',
    messagingSenderId: '447473778417',
    projectId: 'wiragrama-23891',
    authDomain: 'wiragrama-23891.firebaseapp.com',
    storageBucket: 'wiragrama-23891.appspot.com',
    measurementId: 'G-BCGH2RC01D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN2Zto6V1NQIR3Ph7PMaJSOL9QYl1Uquo',
    appId: '1:447473778417:android:5b350ca4343cb20afa7350',
    messagingSenderId: '447473778417',
    projectId: 'wiragrama-23891',
    storageBucket: 'wiragrama-23891.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_WNW58yJmEPHw1F0DjcOtCSEfCSiJ918',
    appId: '1:447473778417:ios:3436f7260539e4effa7350',
    messagingSenderId: '447473778417',
    projectId: 'wiragrama-23891',
    storageBucket: 'wiragrama-23891.appspot.com',
    iosBundleId: 'com.example.wiragrama',
  );
}
